<?php
/**
 * @file
 * asc_events.features.user_permission.inc
 */

/**
 * Implements hook_user_default_permissions().
 */
function asc_events_user_default_permissions() {
  $permissions = array();

  // Exported permission: create asc_event content.
  $permissions['create asc_event content'] = array(
    'name' => 'create asc_event content',
    'roles' => array(
      0 => 'Content Editor',
      1 => 'Content Manager',
      2 => 'Site Administrator',
    ),
    'module' => 'node',
  );

  // Exported permission: delete any asc_event content.
  $permissions['delete any asc_event content'] = array(
    'name' => 'delete any asc_event content',
    'roles' => array(
      0 => 'Content Manager',
      1 => 'Site Administrator',
    ),
    'module' => 'node',
  );

  // Exported permission: delete own asc_event content.
  $permissions['delete own asc_event content'] = array(
    'name' => 'delete own asc_event content',
    'roles' => array(
      0 => 'Content Editor',
      1 => 'Content Manager',
      2 => 'Site Administrator',
    ),
    'module' => 'node',
  );

  // Exported permission: edit any asc_event content.
  $permissions['edit any asc_event content'] = array(
    'name' => 'edit any asc_event content',
    'roles' => array(
      0 => 'Content Editor',
      1 => 'Content Manager',
      2 => 'Site Administrator',
    ),
    'module' => 'node',
  );

  // Exported permission: edit own asc_event content.
  $permissions['edit own asc_event content'] = array(
    'name' => 'edit own asc_event content',
    'roles' => array(
      0 => 'Content Editor',
      1 => 'Content Manager',
      2 => 'Site Administrator',
    ),
    'module' => 'node',
  );

  return $permissions;
}
